name: unison-parser-typechecker
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors

ghc-options: -Wall -fno-warn-name-shadowing -fno-warn-missing-pattern-synonym-signatures

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_parser_typechecker

  dependencies:
    - ListLike
    - aeson
    - async
    - atomic-primops
    - base
    - bytes
    - bytestring
    - concurrent-output
    - containers >= 0.6.3
    - errors
    - extra
    - filelock
    - filepath
    - free
    - generic-lens
    - hashable
    - hashtables
    - lens
    - megaparsec
    - mmorph
    - mtl
    - mutable-containers
    - network-uri
    - nonempty-containers
    - pretty-simple
    - regex-tdfa
    - semialign
    - semigroups
    - servant-client
    - stm
    - text
    - these
    - time
    - transformers
    - unicode-show
    - unison-codebase
    - unison-codebase-sqlite
    - unison-codebase-sqlite-hashing-v2
    - unison-codebase-sync
    - unison-core
    - unison-core1
    - unison-hash
    - unison-hashing-v2
    - unison-prelude
    - unison-pretty-printer
    - unison-sqlite
    - unison-syntax
    - unison-util-base32hex
    - unison-util-bytes
    - unison-util-cache
    - unison-util-recursion
    - unison-util-relation
    - unison-util-rope
    - unison-util-serialization
    - unliftio
    - uuid
    - vector
    - witherable

tests:
  parser-typechecker-tests:
    source-dirs: tests
    main: Suite.hs
    ghc-options: -W -threaded -rtsopts "-with-rtsopts=-N -T" -v0
    dependencies:
      - base
      - code-page
      - containers
      - easytest
      - text
      - unison-core
      - unison-core1
      - unison-hash
      - unison-parser-typechecker
      - unison-prelude
      - unison-pretty-printer
      - unison-syntax
      - unison-util-relation
      - unison-util-rope
      - megaparsec
      - mtl
      - temporary
      - raw-strings-qq
      - unison-hashing-v2
    when:
      - condition: false
        other-modules: Paths_unison_parser_typechecker

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
