name: unison-cli
github: unisonweb/unison
copyright: Copyright (C) 2013-2018 Unison Computing, PBC and contributors

ghc-options: -Wall

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_cli
    - condition: "!os(windows)"
      dependencies: unix
  dependencies:
    - Diff
    - IntervalMap
    - ListLike
    - aeson >= 2.0.0.0
    - aeson-pretty
    - algebraic-graphs
    - ansi-terminal
    - attoparsec
    - base
    - bytestring
    - cmark
    - co-log-core
    - code-page
    - concurrent-output
    - conduit
    - conduit-extra
    - containers >= 0.6.3
    - cryptonite
    - directory
    - either
    - errors
    - extra
    - filepath
    - free
    - friendly-time
    - frontmatter
    - fsnotify
    - generic-lens
    - github
    - haskeline
    - hs-mcp
    - http-client >= 0.7.6
    - http-client-tls
    - http-types
    - ki
    - lens
    - lock-file
    - lsp >= 2.2.0.0
    - lsp-types >= 2.0.2.0
    - megaparsec
    - memory
    - mtl
    - network-simple
    - network-uri
    - nonempty-containers
    - numerals
    - open-browser
    - optparse-applicative >= 0.16.1.0
    - pretty-simple
    - process
    - random-shuffle
    - raw-strings-qq
    - recover-rtti
    - semialign
    - serialise
    - servant
    - servant-client
    - servant-conduit
    - stm
    - stm-chans
    - temporary
    - text
    - text-ansi
    - text-builder
    - text-rope
    - these
    - time
    - transformers
    - unison-codebase
    - unison-codebase-sqlite
    - unison-codebase-sqlite-hashing-v2
    - unison-core
    - unison-core1
    - unison-hash
    - unison-merge
    - unison-parser-typechecker
    - unison-prelude
    - unison-pretty-printer
    - unison-runtime
    - unison-share-api
    - unison-share-projects-api
    - unison-sqlite
    - unison-syntax
    - unison-util-base32hex
    - unison-util-file-embed
    - unison-util-recursion
    - unison-util-relation
    - unliftio
    - uuid
    - vector
    - wai
    - warp
    - witch
    - witherable

tests:
  cli-tests:
    when:
      - condition: false
        other-modules: Paths_unison_cli
    dependencies:
      - base
      - code-page
      - containers
      - cryptonite
      - directory
      - easytest
      - extra
      - here
      - lens
      - lsp
      - lsp-types
      - megaparsec
      - mtl
      - temporary
      - text
      - these
      - unison-cli
      - unison-core
      - unison-core1
      - unison-parser-typechecker
      - unison-prelude
      - unison-pretty-printer
      - unison-syntax
      - unison-util-recursion
      - unliftio
    main: Main.hs
    source-dirs: tests

executables:
  transcripts:
    when:
      - condition: false
        other-modules: Paths_unison_cli
    source-dirs: transcripts
    main: Transcripts.hs
    ghc-options: -threaded -rtsopts "-with-rtsopts=-I0 -N -qn4 -qg1" -v0
    dependencies:
      - base
      - bytestring
      - code-page
      - easytest
      - filepath
      - megaparsec
      - silently
      - text
      - unison-cli
      - unison-parser-typechecker
      - unison-prelude
      - unliftio

default-extensions:
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeOperators
  - ViewPatterns
