name: unison-cli
github: unisonweb/unison
copyright: Copyright (C) 2013-2018 Unison Computing, PBC and contributors

flags:
  optimized:
    manual: true
    default: false

ghc-options: -Wall

dependencies:
  - ListLike
  - aeson
  - async
  - base
  - bytes
  - bytestring
  - configurator
  - containers >= 0.6.3
  - cryptonite
  - directory
  - either
  - errors
  - extra
  - filepath
  - generic-lens
  - haskeline
  - http-client >= 0.7.6
  - http-client-tls
  - http-types
  - jwt
  - lens
  - lock-file
  - megaparsec >= 5.0.0 && < 7.0.0
  - memory
  - mtl
  - network-uri
  - nonempty-containers
  - open-browser
  - random >= 1.2.0
  - regex-tdfa
  - semialign
  - servant
  - servant-client
  - stm
  - text
  - these
  - time
  - transformers
  - unison-codebase
  - unison-codebase-sqlite
  - unison-core1
  - unison-parser-typechecker
  - unison-prelude
  - unison-pretty-printer
  - unison-share-api
  - unison-share-api
  - unison-util
  - unison-util-base32hex
  - unison-util-relation
  - unliftio
  - vector
  - wai
  - warp

library:
  source-dirs: src
  when:
    - condition: '!os(windows)'
      dependencies: unix

tests:
  cli-tests:
    dependencies:
      - code-page
      - easytest
      - here
      - shellmet
      - temporary
      - unison-cli
    main: Main.hs
    source-dirs: tests

executables:
  unison:
    source-dirs: unison
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-I0 -optP-Wno-nonportable-include-path
    dependencies:
      - code-page
      - optparse-applicative >= 0.16.1.0
      - shellmet
      - template-haskell
      - temporary
      - unison-cli

  transcripts:
    source-dirs: transcripts
    main: Transcripts.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -v0
    dependencies:
      - code-page
      - easytest
      - process
      - shellmet
      - unison-cli

  cli-integration-tests:
    source-dirs: integration-tests
    main: Suite.hs
    ghc-options: -W -threaded -rtsopts "-with-rtsopts=-N -T" -v0
    dependencies:
      - code-page
      - easytest
      - process
      - shellmet
      - time
    build-tools:
      - unison-cli:unison

when:
  - condition: flag(optimized)
    ghc-options: -O2 -funbox-strict-fields

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns
