name: unison-cli
github: unisonweb/unison
copyright: Copyright (C) 2013-2018 Unison Computing, PBC and contributors

flags:
  optimized:
    manual: true
    default: false

ghc-options: -Wall

dependencies:
  - base
  - text
  - unison-parser-typechecker
  - unison-prelude
  - megaparsec
  - directory

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_cli
    - condition: "!os(windows)"
      dependencies: unix
  dependencies:
    - code-page
    - optparse-applicative >= 0.16.1.0
    - temporary
    - IntervalMap
    - ListLike
    - aeson >= 2.0.0.0
    - aeson-pretty
    - ansi-terminal
    - async
    - bytestring
    - cmark
    - co-log-core
    - code-page
    - concurrent-output
    - containers >= 0.6.3
    - cryptonite
    - either
    - errors
    - extra
    - filepath
    - free
    - friendly-time
    - fsnotify
    - generic-lens
    - haskeline
    - http-client >= 0.7.6
    - http-client-tls
    - http-types
    - ki
    - lens
    - lock-file
    - lsp >= 2.2.0.0
    - lsp-types >= 2.0.2.0
    - memory
    - mtl
    - network-simple
    - network-uri
    - nonempty-containers
    - numerals
    - open-browser
    - optparse-applicative >= 0.16.1.0
    - pretty-simple
    - process
    - random-shuffle
    - recover-rtti
    - regex-tdfa
    - semialign
    - servant
    - servant-client
    - stm
    - temporary
    - text-ansi
    - text-builder
    - text-rope
    - these
    - time
    - transformers
    - unliftio
    - unison-codebase
    - unison-codebase-sqlite
    - unison-codebase-sqlite-hashing-v2
    - unison-core
    - unison-core1
    - unison-hash
    - unison-merge
    - unison-parser-typechecker
    - unison-pretty-printer
    - unison-runtime
    - unison-share-api
    - unison-share-projects-api
    - unison-sqlite
    - unison-syntax
    - unison-util-base32hex
    - unison-util-recursion
    - unison-util-relation
    - uuid
    - vector
    - wai
    - warp
    - witch
    - witherable

tests:
  cli-tests:
    when:
      - condition: false
        other-modules: Paths_unison_cli
    dependencies:
      - code-page
      - containers
      - cryptonite
      - easytest
      - extra
      - here
      - lens
      - lsp-types
      - temporary
      - these
      - unison-cli
      - unison-core
      - unison-core1
      - unison-parser-typechecker
      - unison-pretty-printer
      - unison-syntax
      - unison-util-recursion
    main: Main.hs
    source-dirs: tests

executables:
  transcripts:
    when:
      - condition: false
        other-modules: Paths_unison_cli
    source-dirs: transcripts
    main: Transcripts.hs
    ghc-options: -threaded -rtsopts "-with-rtsopts=-I0 -N -qn4 -qg1" -v0
    dependencies:
      - code-page
      - easytest
      - filepath
      - silently
      - unison-cli
      - unliftio

when:
  - condition: flag(optimized)
    ghc-options: -O2 -funbox-strict-fields

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns
