#!/usr/bin/env bash

$(nix-build env.nix -A unisonPackages.ghc7101.unison-node --no-out-link)/bin/node &
echo The editor is at: file://$(nix-build env.nix -A unisonPackages.ghcjs.unison-editor --no-out-link)/bin/editor.jsexe/index.html
