## To minimize building of Haskell packages, this should match the LTS used by the rev of Nixpkgs that we’re on
resolver: lts-24.21 # GHC 9.10.3

## We intentionally disable Nix integration when running in a Nix shell.
notify-if-nix-on-path: false
## We pin a specific Stack version when possible. We shouldn’t then tell contributors to upgrade from there.
recommend-stack-upgrade: false

allow-different-user: true

build:
  interleaved-output: false

packages:
  - codebase2/codebase
  - codebase2/codebase-sqlite
  - codebase2/codebase-sqlite-hashing-v2
  - codebase2/codebase-sync
  - codebase2/core
  - codebase2/util-serialization
  - codebase2/util-term
  - lib/orphans/network-uri-orphans-sqlite
  - lib/orphans/unison-core-orphans-sqlite
  - lib/orphans/unison-hash-orphans-aeson
  - lib/orphans/unison-hash-orphans-sqlite
  - lib/orphans/uuid-orphans-sqlite
  - lib/unison-credentials
  - lib/unison-dynlib
  - lib/unison-hash
  - lib/unison-hashing
  - lib/unison-prelude
  - lib/unison-pretty-printer
  - lib/unison-sqlite
  - lib/unison-util-base32hex
  - lib/unison-util-bytes
  - lib/unison-util-cache
  - lib/unison-util-diff3
  - lib/unison-util-file-embed
  - lib/unison-util-recursion
  - lib/unison-util-relation
  - lib/unison-util-rope
  - parser-typechecker
  - unison-cli
  - unison-cli-integration
  - unison-cli-main
  - unison-core
  - unison-hashing-v2
  - unison-merge
  - unison-runtime
  - unison-share-api
  - unison-share-projects-api
  - unison-syntax
  - yaks/easytest

extra-deps:
  # This custom Haskeline alters ANSI rendering on Windows.
  # If changing the haskeline dependency, please ensure color renders properly in a
  # Windows terminal.
  # https://github.com/judah/haskeline/pull/126
  - github: unisonweb/haskeline
    commit: d7791c203f71e7da93c9570b51519bd31eec47d6 # branch unison-26-01-28
  - github: ChrisPenner/hs-mcp
    commit: d8564c70ca09e333b7ce1717d1ac97a62d62966c

  # not in stackage
  - fuzzyfind-3.0.2@sha256:0fcd64eb1016fe0d0232abc26b2b80b32d676707ff41d155a28df8a9572603d4,1921
  - lock-file-0.7.0.0@sha256:3ad84b5e454145e1d928063b56abb96db24a99a21b493989520e58fa0ab37b00,4484
  - monad-validate-1.3.0.0@sha256:eb6ddd5c9cf72ff0563cba604fa00291376e96138fdb4932d00ff3a99d66706e,2605
  - numerals-0.4.1@sha256:f138b4a0efbde3b3c6cbccb788eff683cb8a5d046f449729712fd174c5ee8a78,11430
  - network-udp-0.0.0@sha256:408d2d4fa1a25e49e95752ee124cca641993404bb133ae10fb81daef22d876ae,1075
  - tls-2.4.2@sha256:39b5cf652f287baa3de345b56122533b75ba88d4fac1027ec313046a52086451,7686
  - crypton-1.1.2@sha256:98681a0ac0c09adda61469354e0853deaf21ff1a2234d6294fdb0e9a5d2f976d,15142
  - crypton-asn1-encoding-0.10.0@sha256:45494a1723a047a815d0d620481c1028dca28a4ea5cf2554868687da90753961,2497
  - crypton-asn1-types-0.4.1@sha256:02f3ec473011b3da92f7bf738bea19cadf88a6470b25a6cb5042216c7549c912,1326
  - crypton-x509-1.9.0@sha256:66a1bc2a47db64c19f83b93667b79508c1790d72fc6f11acc79dcf40459cee03,2010
  - crypton-x509-store-1.9.0@sha256:9746160b993c24c175e560e27051dfe4616c6413014712776f1297e2ca8bba8a,1700
  - crypton-x509-validation-1.9.0@sha256:dd0b5b88eaf8aaf3675e7cf7f7c062822be349561dcff25d1266b8ade7364233,2030
  - hpke-0.1.0@sha256:fb107670a0aeb91b4626e0b1dff4e7ec3342e48931cc994938d95af1a23f645d,1801
  - mlkem-0.2.0.0@sha256:c51d0779dc69ff375420444ffa2f0ce9229bd8e967eb4b17216c0fa85a53984f,4703
  - ram-0.22.0@sha256:f6ce64a025929eb6ce42deeb80d072960a9ea2d83b9b9b28de668cc2b623127c,2814
  - crypton-asn1-parse-0.10.0@sha256:4a2cfc4980957d1a279ef69137ee5f665c247ccd8bb962812d5b071d543893fb,1359
  - time-hourglass-0.3.0@sha256:ee02356fe24919ec43ae17fc0007398c2fd0bbe822833b2d7a9c849537b90580,3114

flags:
  haskeline:
    terminfo: false

allow-newer: true
allow-newer-deps:
  - crypton-connection
  - fuzzyfind
  - lock-file
  - numerals

ghc-options:
  # All packages
  "$locals": -Wall -Werror -Wwarn=x-partial -Wno-missing-pattern-synonym-signatures -Wno-name-shadowing -Wunused-packages -fprint-expanded-synonyms -funbox-strict-fields -fwrite-ide-info # -freverse-errors

  # See https://github.com/haskell/haskell-language-server/issues/208
  #
  # -fno-omit-yields allows non-allocating loops to be preempted by the
  # GHC scheduler. Building all dependencies with it results in fewer
  # opportunities for uninterruptible loops.
  "$everything": -haddock -fno-omit-yields

  statistics: -fsimpl-tick-factor=10000 # statistics fails on GHC 9 without this, https://github.com/haskell/statistics/issues/173
