flags: {}

allow-newer: true # async package has needlessly strict upper bound

packages:
- yaks/parsec-layout
- yaks/easytest
- parser-typechecker

#compiler-check: match-exact
resolver: lts-11.9
compiler: ghc-8.4.2

extra-deps:
- base58-bytestring-0.1.0

ghc-options:
 # All packages
 "$locals": -Werror -freverse-errors
