flags:
  haskeline:
    terminfo: false

allow-different-user: true

build:
  interleaved-output: false

packages:
- codebase2/codebase
- codebase2/codebase-sqlite
- codebase2/codebase-sqlite-hashing-v2
- codebase2/codebase-sync
- codebase2/core
- codebase2/util-serialization
- codebase2/util-term
- lib/orphans/network-uri-orphans-sqlite
- lib/orphans/unison-core-orphans-sqlite
- lib/orphans/unison-hash-orphans-aeson
- lib/orphans/unison-hash-orphans-sqlite
- lib/orphans/uuid-orphans-sqlite
- lib/unison-hash
- lib/unison-hashing
- lib/unison-prelude
- lib/unison-pretty-printer
- lib/unison-sqlite
- lib/unison-util-base32hex
- lib/unison-util-bytes
- lib/unison-util-cache
- lib/unison-util-relation
- lib/unison-util-rope
- parser-typechecker
- unison-cli
- unison-core
- unison-hashing-v2
- unison-share-api
- unison-share-projects-api
- unison-syntax
- yaks/easytest

resolver: nightly-2023-05-20
allow-newer: true
# NanoID-3.3.0 disallows base 4.17 from ghc 9.4
# base32-0.2.2.0 disallows base 4.17, text 2.x
# fuzzyfind-3.0.1 disallows criterion 1.6, text 2.x
# recover-rtti-0.4.2 disallows aeson 2.1.x, base 4.17, ghc-heap 9.4, primitive 0.8, vector 0.13
# shellmet-0.0.4.1 disallows base 4.17

extra-deps:
# This custom build supports defining blocks for deeper keys without explicitly nesting blocks
- github: unisonweb/configurator
  commit: e47e9e9fe1f576f8c835183b9def52d73c01327a

# This custom Haskeline alters ANSI rendering on Windows.
# If changing the haskeline dependency, please ensure color renders properly in a
# Windows terminal.
# https://github.com/judah/haskeline/pull/126
- github: unisonweb/haskeline
  commit: 9275eea7982dabbf47be2ba078ced669ae7ef3d5

# snapshot version is too new
- fsnotify-0.3.0.1 # vs 0.4.1.0
- network-3.1.2.7 # 3.1.3.0 doesn't seem to build in GH actions windows-2019

# in lts-20 but not in snapshot
- NanoID-3.3.0
- shellmet-0.0.4.1
- base32-0.2.2.0

# not in stackage
- fuzzyfind-3.0.1
- guid-0.1.0@sha256:a7c975be473f6f142d5cc1b39bc807a99043d20b1bb0873fdfe7a3ce84d2faf1,1078
- lock-file-0.7.0.0@sha256:3ad84b5e454145e1d928063b56abb96db24a99a21b493989520e58fa0ab37b00,4484
- monad-validate-1.2.0.0@sha256:9850f408431098b28806dd464b6825a88a0b56c84f380d7fe0454c1df9d6f881,3505
- recover-rtti-0.4.2@sha256:c179a303921126d8d782264e14f386c96e54a270df74be002e4c4ec3c8c7aebd,4529

ghc-options:
 # All packages
 "$locals": -Wall -Werror -Wno-name-shadowing -Wno-missing-pattern-synonym-signatures -fprint-expanded-synonyms -fwrite-ide-info #-freverse-errors

 # See https://github.com/haskell/haskell-language-server/issues/208
 "$everything": -haddock
