name:                json-diff
version:             0.1.0.0
github:              "githubuser/json-diff"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/json-diff#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-extra
- free
- hashable
- containers
- unordered-containers
- lens
- recursion-schemes
- mtl
- transformers
- semialign
- these
- distributive
- adjunctions
- generic-data
- comonad
- text
- unison-parser-typechecker
- vector
- pretty-simple
- random

library:
  source-dirs: src

executables:
  json-diff-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-diff

tests:
  json-diff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-diff
