#!/usr/bin/env bash
set -eu

if ! type -P nix-shell >/dev/null ; then
  . ~/.nix-profile/etc/profile.d/nix.sh
  if ! type -P nix-shell >/dev/null ; then
    echo "It looks like Nix isn't working.  Please make sure you can run nix-shell, then retry the $0, or submit an issue at $REPO/issues"
    exit 1
  fi
fi

PLATFORMS=$(eval "echo $(nix-instantiate --eval -E '(import ./nixpkgs {}).stdenv.lib.concatStringsSep " " (import ./.).platforms')")

ROOTS=$(nix-build -I . -j 8 --no-out-link -E "import ./shell.nix {}")

nix-copy-closure --gzip --to "$1" $ROOTS
