#!/bin/bash

installdir="$(stack path --local-install-root)"

echo "Emitting the following html to editor.html:"
echo

cat >editor.html <<EOL
<!DOCTYPE html>
<html>
  <head>
    <script language="javascript" src="$installdir/bin/editor.jsexe/rts.js"></script>
    <script language="javascript" src="$installdir/bin/editor.jsexe/lib.js"></script>
    <script language="javascript" src="$installdir/bin/editor.jsexe/out.js"></script>
    <link rel="stylesheet" type="text/css" href="fonts/fira-code.webfont/webfont.css">
    <link rel="stylesheet" type="text/css" href="stylesheets/styles.css">
  </head>
  <body>
  </body>
  <script language="javascript" src="$installdir/bin/editor.jsexe/runmain.js" defer></script>
</html>
EOL

cat editor.html
