name: unison-runtime
github: unisonweb/unison
copyright: Copyright (C) 2013-2024 Unison Computing, PBC and contributors

ghc-options: -Wall -O0

flags:
  optimized:
    manual: true
    default: true
  arraychecks:
    manual: true
    default: false

when:
  - condition: flag(optimized)
    ghc-options: -funbox-strict-fields -O2
  - condition: flag(arraychecks)
    cpp-options: -DARRAY_CHECK

executables:
  machine2:
    source-dirs: exes
    main: Main.hs
    ghc-options: -funbox-strict-fields -O2 -threaded -rtsopts "-with-rtsopts=-I0 -N -qn4 -qg1 -T" -optP-Wno-nonportable-include-path
    dependencies:
      - base
      - primitive

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_runtime

  dependencies:
    - asn1-encoding
    - asn1-types
    - atomic-primops
    - base
    - binary
    - bytes
    - bytestring
    - cereal
    - clock
    - containers >= 0.6.3
    - cryptonite
    - data-default
    - data-memocombinators
    - deepseq
    - directory
    - exceptions
    - filepath
    - iproute
    - lens
    - memory
    - mmorph
    - mtl
    - murmur-hash
    - network
    - network-simple
    - network-udp
    - pem
    - primitive
    - process
    - raw-strings-qq
    - safe-exceptions
    - stm
    - tagged
    - temporary
    - text
    - time
    - tls
    - unison-codebase-sqlite
    - unison-core
    - unison-core1
    - unison-hash
    - unison-parser-typechecker
    - unison-prelude
    - unison-pretty-printer
    - unison-syntax
    - unison-util-bytes
    - unliftio
    - vector
    - crypton-x509
    - crypton-x509-store
    - crypton-x509-system

tests:
  runtime-tests:
    source-dirs: tests
    main: Suite.hs
    ghc-options: -W -threaded -rtsopts "-with-rtsopts=-N -T" -v0
    when:
      - condition: false
        other-modules: Paths_unison_parser_typechecker
    dependencies:
      - base
      - code-page
      - containers
      - cryptonite
      - directory
      - easytest
      - filemanip
      - filepath
      - hex-text
      - lens
      - megaparsec
      - mtl
      - stm
      - text
      - unison-core1
      - unison-parser-typechecker
      - unison-prelude
      - unison-pretty-printer
      - unison-runtime
      - unison-syntax

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
