name: unison-util-serialization

library:
  source-dirs: .
  when:
    - condition: false
      other-modules: Paths_unison_util_serialization

dependencies:
  - base
  - bytes
  - bytestring
  - containers
  - filepath
  - text
  - text-short
  - unliftio
  - vector
