name: unison-hashing-v2
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors

ghc-options: -Wall

dependencies:
  - base
  - bytestring
  - containers
  - cryptonite
  - lens
  - memory
  - semialign
  - text
  - unison-core1
  - unison-prelude
  - unison-util
  - unison-util-base32hex
  - unison-util-relation

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_hashing_v2

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns
