#!/usr/bin/env bash
set -euo pipefail
SCRIPTDIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"

source "$SCRIPTDIR/check-version.bash"

if version-equals weeder "2.10.0"; then
    ## We `cd` so Weeder can find all the files.
    cd "$SCRIPTDIR/.."
    ## Weeder gets confused by HIE files in the Direnv cache, but doesn’t let us exclude a directory from HIE search
    ## (ocharles/weeder#201). So this enumerates the directories we _do_ want to search.
    ##
    ## TODO: Populate the `--hie-directory` list with something like
    ##     > find . -type d -name ".stack-work" -exec dirname "{}" \; -printf "--hie-directory %p\0" |
    ##     >   xargs -0 weeder --no-default-fields --require-hs-files
    ##       but that particular incantation requires GNU find for `-printf`, which isn’t on macOS.
    weeder \
        --no-default-fields --require-hs-files \
        --hie-directory ./codebase2 \
        --hie-directory ./lib \
        --hie-directory ./parser-typechecker \
        --hie-directory ./unison-cli \
        --hie-directory ./unison-cli-integration \
        --hie-directory ./unison-cli-main \
        --hie-directory ./unison-core \
        --hie-directory ./unison-hashing-v2 \
        --hie-directory ./unison-merge \
        --hie-directory ./unison-runtime \
        --hie-directory ./unison-share-api \
        --hie-directory ./unison-share-projects-api \
        --hie-directory ./unison-syntax \
        --hie-directory ./yaks
fi
