#!/usr/bin/env bash
set -euo pipefail
SCRIPTDIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"

source "$SCRIPTDIR/check-version.bash"

mode=${1:-check}

if version-equals ormolu "0.7.7.0"; then
    ## We `cd` so Ormolu can find its .ormolu configuration.
    cd "$SCRIPTDIR/.."
    find . -name '*.hs' -not -path "*/dist-newstyle/*" -not -path "*/.stack-work/*" -print0 \
        | xargs -0 ormolu --check-idempotence --mode "${mode}"
fi
