name: unison-core1
github: unisonweb/unison
copyright: Copyright (C) 2013-2018 Unison Computing, PBC and contributors

library:
  when:
    - condition: false
      other-modules: Paths_unison_core1
  source-dirs: src
  ghc-options: -Wall -fno-warn-name-shadowing -fno-warn-missing-pattern-synonym-signatures -funbox-strict-fields
  dependencies:
    - base
    - bytestring
    - containers >= 0.6.3
    - nonempty-containers
    - cryptonite
    - extra
    - fuzzyfind
    - generic-lens
    - lens
    - megaparsec
    - memory
    - mtl
    - rfc5051
    - semialign
    - semigroups
    - text
    - text-builder
    - these
    - unison-core
    - unison-hash
    - unison-prelude
    - unison-util-relation
    - witch

tests:
  tests:
    when:
      - condition: false
        other-modules: Paths_unison_core1
    dependencies:
      - base
      - code-page
      - easytest
      - text
      - these
      - unison-core
      - unison-core1
      - unison-prelude
    main: Main.hs
    source-dirs: test

default-extensions:
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedStrings
  - OverloadedRecordDot
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns
