name: unison-share-api
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_share_api

dependencies:
  - NanoID
  - aeson
  - async
  - base
  - binary
  - bytestring
  - containers
  - directory
  - errors
  - extra
  - filepath
  - fuzzyfind
  - http-media
  - http-types
  - jose
  - jwt
  - lens
  - lucid
  - memory
  - mtl
  - mwc-random
  - network
  - nonempty-containers
  - openapi3
  - regex-tdfa
  - servant
  - servant-docs
  - servant-openapi3
  - servant-server
  - servant-auth
  - text
  - transformers
  - unison-codebase
  - unison-codebase-sqlite
  - unison-core1
  - unison-parser-typechecker
  - unison-prelude
  - unison-pretty-printer
  - unison-util
  - unison-util-base32hex
  - unison-util-base32hex-orphans-aeson
  - unison-util-relation
  - unison-sqlite
  - unison-syntax
  - unliftio
  - unordered-containers
  - uri-encode
  - utf8-string
  - vector
  - wai
  - warp
  - yaml

ghc-options:
  -Wall

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeOperators
  - ViewPatterns
