name: unison-share-api
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_share_api

tests:
  unison-share-api-tests:
    when:
      - condition: false
        other-modules: Paths_unison_share_api
    dependencies:
      - code-page
      - easytest
      - hedgehog
      - unison-share-api
    main: Main.hs
    source-dirs: tests

dependencies:
  - aeson >= 2.0.0.0
  - async
  - base
  - binary
  - bytes
  - bytestring
  - cborg
  - containers
  - cryptonite
  - Diff
  - directory
  - errors
  - extra
  - filepath
  - fuzzyfind
  - http-media
  - http-types
  - jose
  - jwt
  - lens
  - lucid
  - memory
  - mtl
  - mwc-random
  - nonempty-containers
  - openapi3
  - regex-tdfa
  - serialise
  - servant
  - servant-docs
  - servant-openapi3
  - servant-server
  - servant-auth
  - text
  - transformers
  - unison-codebase
  - unison-codebase-sqlite
  - unison-codebase-sqlite-hashing-v2
  - unison-core
  - unison-core1
  - unison-hash
  - unison-hash-orphans-aeson
  - unison-hashing-v2
  - unison-parser-typechecker
  - unison-prelude
  - unison-pretty-printer
  - unison-util-base32hex
  - unison-util-relation
  - unison-share-projects-api
  - unison-sqlite
  - unison-syntax
  - unliftio
  - unordered-containers
  - uri-encode
  - utf8-string
  - vector
  - wai
  - wai-cors
  - warp
  - yaml

ghc-options:
  -Wall

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators
  - ViewPatterns
  - ImportQualifiedPost
