name: unison-share-api
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors


library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_share_api

  dependencies:
    - aeson >= 2.0.0.0
    - base
    - binary
    - bytes
    - bytestring
    - cborg
    - containers
    - conduit
    - Diff
    - directory
    - errors
    - extra
    - filepath
    - fuzzyfind
    - hs-mcp
    - http-media
    - http-types
    - ki-unlifted
    - lens
    - lucid
    - memory
    - mtl
    - nonempty-containers
    - openapi3
    - regex-tdfa
    - serialise
    - servant
    - servant-docs
    - servant-openapi3
    - servant-server
    - servant-websockets
    - stm-chans
    - text
    - time
    - transformers
    - unison-codebase
    - unison-codebase-sqlite
    - unison-codebase-sqlite-hashing-v2
    - unison-core
    - unison-core1
    - unison-hash
    - unison-hash-orphans-aeson
    - unison-hashing-v2
    - unison-parser-typechecker
    - unison-prelude
    - unison-pretty-printer
    - unison-runtime
    - unison-util-recursion
    - unison-util-relation
    - unison-util-base32hex
    - unison-share-projects-api
    - unison-sqlite
    - unison-syntax
    - unliftio
    - uri-encode
    - utf8-string
    - vector
    - wai
    - websockets
    - wai-cors
    - warp
    - yaml

tests:
  unison-share-api-tests:
    when:
      - condition: false
        other-modules: Paths_unison_share_api
    dependencies:
      - code-page
      - easytest
      - hedgehog
      - unison-share-api
      - base
      - bytestring
      - raw-strings-qq
      - serialise
      - text
      - unison-hash
      - unison-prelude
      - unison-codebase-sqlite
      - unison-pretty-printer
      - vector

    main: Main.hs
    source-dirs: tests

ghc-options:
  -Wall

default-extensions:
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators
  - ViewPatterns
