name: unison-codebase
github: unisonweb/unison

dependencies:
  - base
  - containers
  - generic-lens
  - lens
  - mtl
  - text
  - time
  - unison-core
  - unison-hash
  - unison-prelude
  - unison-util-base32hex

library:
  source-dirs: .
  when:
    - condition: false
      other-modules: Paths_unison_codebase

default-extensions:
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns

language: GHC2021
