### Cabal is not supported by Unison. This workflow helps us keep the contributed cabal.project file in a good state,
### but it is not a required workflow.

name: Cabal

defaults:
  run:
    shell: bash

on:
  # Run on the post-merge result of every push to a PR that changes one of the relevant build files.
  pull_request:
    paths:
      - '**.cabal'
      - '**/cabal.project'
      - '**/stack.yaml'
  # Allow manual runs
  workflow_dispatch:

jobs:
  smoke-test:
    # Only build on one platform, because we’re mostly just checking that the cabal.project file is sane.
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.5' # Should match the version implied by the resolver in ../../stack.yaml.
          cabal-version: '3.10.3.0' # Should match the version in ../../.vscode/settings.json.

      - run: cabal freeze --project-file contrib/cabal.project

      - name: cache Cabal build artifacts
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          # stack.yaml is included, because if it changed, it indicates that cabal.project probably needs to change.
          key: cabal-freeze-${{ hashFiles('**/cabal.project.freeze') }}
          restore-keys: |
            cabal-freeze

      # --only-configure skips some build steps, but should ensure all dependencies are correct.
      - run: cabal build all --only-configure --project-file contrib/cabal.project
